language: ruby
install:
  - gem uninstall bundler
  - gem install bundler --version '1.7.4'
rvm: 
- 2.4.1
services: 
  - postgresql
before_script:
  - psql -c 'create database MoveTime_test;' -U postgres
script:
  - bundle exec rspec